### ISSUE TITLE
Edit the readme since CE now needs to be installed from source again

### ISSUE THREAD

**Issue by double-fault** [SOBotics/Botpy#17]
CE's latest version is now not on PyPi, and it need to be installed from source. Reflect this in the docs/readme.

**Comment by tripleee** [comment]
The code should work fine with the currently published version if you don't attempt to exercise the strictly optional `send_aggressively` feature. This should probably be documented per se; though hopefully, we could probably just wait for upstream to publish a new release and then simply document the version requirement by way of a versioned dependency in `requirements.txt` / `setup.py`

**Comment by tripleee** [comment]
Updated as part of #27
