### ISSUE TITLE
Modify post_global_message to take same parameters as post

### ISSUE THREAD

**Issue by AWegnerGitHub** [SOBotics/Botpy#30]
[`post_global_message`](https://github.com/SOBotics/Botpy/blob/master/Source/Bot.py#L281) takes a single parameter (`message`). The [`post`](https://github.com/SOBotics/Botpy/blob/master/Source/Command.py#L29) method in a `Command` takes two parameters. 

Can the `post_global_message` be modified to also include the boolean `length_check`?

**Comment by double-fault** [comment]
Fixed in 0.7.10.
