### ISSUE TITLE
Odd copyright in LICENSE

### ISSUE THREAD

**Issue by tripleee** [SOBotics/Botpy#5]
https://github.com/SOBotics/Botpy/blob/master/LICENSE#L4 says

> Copyright (C) 2018 Ashish Ahuja (Fortunate-MAN) <ashish.ahuja@sobotics.org> 

My reading of https://en.wikipedia.org/wiki/WTFPL suggests that this is a copyright statement _for the license itself_ and that it should probably say it's (C) 2004 Sam Hocevar <sam@hocevar.net>

The instructions at http://www.wtfpl.net/faq/ vaguely supports this interpretation; in particular, the color-coded explanation of the license terms highlights section 2 as "the rules for the license" and includes the copyright statement.

**Comment by double-fault** [comment]
Most licenses have the copyright of the organization or the person who wrote the code, so I followed that line of thinking and put my own name. I'm not very sure about this, and the website or the wiki page is not very clear. I'll research about this a bit on the weekend; WTFPL is not a very tested license and I'm kinda busy nowadays.

Thanks for bringing this to my attention!

**Comment by tripleee** [comment]
Would switching to a mainstream license like Apache be acceptable to you? That would remove the problem and possibly lower the threshold to contribute for people who find this license murky. As long as there are only two contributors this should be undramatic, though the old versions need to remain under their original license.

**Comment by double-fault** [comment]
@tripleee I'd prefer not to, sorry. I kept WTFPL as the license since I wrote this library for fun and didn't want to pose restrictions on people using it, and however free licenses like Apache and MIT are, they do have conditions; I just want people to use it as they wish.

**Comment by tripleee** [comment]
Posted a question: https://opensource.stackexchange.com/questions/8073/modifying-the-copyright-statement-in-wtfpl

For another take on similar licenses, see also https://opensource.stackexchange.com/questions/1359/should-i-use-the-wtfpl-for-my-floss-project

**Comment by jdd-software** [comment]
As I read it, but I have asked for clarification on opensource, this could be a valid solution, to keep it all in 1 file and have Ashish original licenze idea:

---
Copyright (C) 2018 Ashish Ahuja (Fortunate-MAN) <ashish.ahuja@sobotics.org> 
This work is free.  It comes without any warranty, to the extent permitted by applicable law. 
You can redistribute it and/or modify it under the terms of the Do What The Fuck You Want To Public License, Version 2, as published by Sam Hocevar. 

  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                    Version 2, December 2004 
.... original licenze with Sam's copyright statement follows.

*I edited to add no warranty, that can be wise*

**Comment by jdd-software** [comment]
I have created a push request https://github.com/SOBotics/Botpy/pull/15/files with these changes.

Probably if others are contributing it could be nice to add "others" in copyright notice, hence only adding the text "and others"


Copyright..Ashish... and others.

But I will leave this to Ashish

**Comment by double-fault** [comment]
@tripleee @jdd-software thanks a lot! That, I guess, clarifies the issue; I'm gonna go ahead and merge the PR.

Looks like I had forgotten about this issue; extremely sorry 'bout that!

**Comment by double-fault** [comment]
@jdd-software Should I change the copyright statement to my name and others, or just change it to SOBotics, like other projects have done?

**Comment by jdd-software** [comment]
@fortunate-man as you wish, the "and others" is one solution to give credits to any other future contributore's . People may add personal copyright in code that they submit. I think also that the "and others" solution is nice so I have no personal preference.

**Comment by double-fault** [comment]
@jdd-software @tripleee I've edited the copyright statement; sorry for the delay. Thanks for your suggestions!
